#!/usr/bin/env bash

set -ex

# This script is invoked during CI build with the following arguments:
target_image_name="$1"
app_name="$2"
app_version="$3"

cd ci/predeploy
docker build --build-arg APP_NAME="${app_name}" --build-arg APP_VERSION="${app_version}" -t "${target_image_name}" .

